//
//  DataManager.swift
//  NBAapp
//
//  Created by Станислав Буйновский on 12.11.2021.
//

import Foundation

class DataManager {
    static let shared = DataManager()
    
    //MARK: - news array
    let news: [[String: String]] = [
        ["Id": "1",
         "Title": "Lavigne and DeRozan repeated the achievement of Jordan and Pippen",
         "Subtitle": "Zach Lavigne and DeMar DeRozan became the second duo in Chicago history to score 20+ points in seven consecutive games. The only duo Bulls, which previously succeeded, were the legendary Michael Jordan and Scotty Pippen. Chicago kicked off the 2021/22 season with an 8-3 record and are second in the Eastern Conference.",
         "Date": "12-11-2021",
         "Source": "Bleacher Report",
         "Image": "image1"],
        ["Id": "2",
         "Title": "Alex Caruso leads the NBA in interceptions, ranking 120th in playing time",
         "Subtitle": "Chicago defender Alex Caruso made 6 interceptions in todays game against Dallas (117: 107). In total, Caruso makes 2.6 steals per match per season, ranking first among all NBA players in this indicator. It is noteworthy that in terms of average playing time, the Bulls defender is only 120th in the league. Caruso joined the Chicago squad this summer, moving from the Lakers as a free agent. In the 2021/22 regular season, the defender averages 8.5 points and 3.6 assists, attacking from beyond the arc with a 40.7 percentage point." ,
         "Date": "11-11-2021",
         "Source": "NBA on ESPN",
         "Image": "image2"],
        ["Id": "3",
         "Title": "Terrence Ferguson may continue his career at AEK",
         "Subtitle": "Former Oklahoma player Terrence Ferguson (23 years old, 198 cm) is close to signing with Greek AEK. The American defender played for Philadelphia last season. In March, he was traded to New York and then expelled. In total, Ferguson has 204 NBA games with 4.5 points and 1.3 rebounds.",
         "Date": "10-11-2021",
         "Source": "Twitter Luca D'Alessandro",
         "Image": "image3"],
        ["Id": "4",
         "Title": "Russell Westbrook makes a loss by throwing the ball into the head of Anthony Davis",
         "Subtitle": "Lakers point guard Russell Westbrook has triple-double with 8 losses to Heat (120: 117 OT). One of the losses occurred in the third quarter, when Westbrook unexpectedly threw the ball at close range at the head of teammate Anthony Davis. Westbrook is hitting 5.3 losses per match this season.",
         "Date": "11-11-2021",
         "Source": "Clutch Points",
         "Image": "image4"],
        ["Id": "5",
         "Title": "Clay Thompson announced his upcoming comeback on Instagram",
         "Subtitle": "Golden State Star Defender Clay Thompson posted a photo of himself from practice and announced that he is approaching his debut this season. “Hey Warriors fans, I'm on my way. Show a little patience, the basketball player wrote. Earlier it was reported that Thompson could return to service on December 20 or 23. Thompson missed two seasons in a row as a result of serious injuries.",
         "Date": "12-11-2021",
         "Source": "Twitter Hoop Central",
         "Image": "image5"],
        ["Id": "6",
         "Title": "Miles Turner: 'Gobert played dirty against me'",
         "Subtitle": "Indiana center Miles Turner expressed the opinion that the brawl during the team's match against Utah was the fault of his colleague Rudy Gobert. “I think Gobert played dirty against me. When he grabbed my shorts, I had to react and stand up for myself in such a situation, - said Turner. Turner pushed Gobert away in response, the players grappled, teammates joined them. In addition to Gobert and Turner, Joe Ingles and Donovan Mitchell from Jazz also earned removals.",
         "Date": "12-11-2021",
         "Source": "Clutch Points",
         "Image": "image6"],
        ["Id": "7",
         "Title": "John Wall's workout video published",
         "Subtitle": "A video of the training of Houston point guard John Wall has been leaked online, showing that the 31-year-old is in good shape. In the offseason, Wall and the Rockets agreed to work together to find a new team for the player. At the same time, the club does not intend to buy out the contract, in which two years and $ 91.7 million remained. The parties agreed that Wall will not participate in the team's matches in the 2021/22 season. Houston acquired Wall last year through Russell Westbrook's trade to Washington.",
         "Date": "10-11-2021",
         "Source": "Twitter Overtime",
         "Image": "image7"],
        ["Id": "8",
         "Title": "Charles Barkley thanks Kevin Durant for a funny episode live",
         "Subtitle": "Inside the NBA presenter Charles Barkley, in a video link with Brooklyn striker Kevin Durant, recalled a funny episode that happened at the end of last season. Then, during a flash interview after the match, Barkley asked Durant a detailed question, to which the Nets leader answered with one short word: Yes. Kevin explained that at that moment he assumed that this was not the question itself, but only a statement preceding it, and therefore reacted in this way. “It was a misunderstanding,” Durant said.",
         "Date": "10-11-2021",
         "Source": "NBA on TNT",
         "Image": "image8"],
        ["Id": "9",
         "Title": "Gary Payton II hammered over from Steph Curry's cross",
         "Subtitle": "Warriors defender Gary Payton II continued his streak of spectacular dunks against Minnesota. Payton II threw in an overhead strike from Steph Curry in a quick attack. Payton II had several dunks in the past, after which his legendary father, Gary Payton, speculated about his athletic ability.",
         "Date" : "11-11-2021",
         "Source": "Valery Levkin",
         "Image": "image9"],
        ["Id": "10",
         "Title": "Danny Ainge may replace Neil Olshey as general manager of Portland",
         "Subtitle": "If Neil Olshey steps down as president of basketball operations and general manager of Portland, former Boston chief Danny Ainge could take his place, sports columnist Howard Beck said. The Blazers are currently investigating Olsha. The functionary is accused of inappropriate behavior in the workplace. Ainge became a consultant for the Celtics after resigning from his job at the club's management last summer. He was replaced by former head coach Brad Stevens. Ainge has been Boston's general manager since 2012.",
         "Date": "10-11-2021",
         "Source": "open.spotify.com",
         "Image": "image10"],
        ["Id": "11",
         "Title": "Scottie Pippen: Brooklyn May Win The Championship Without Kyrie Irving",
         "Subtitle": "Six-time NBA Chicago champion Scotty Pippen believes Brooklyn can win the title without Kyrie Irving. “If James Harden gets in shape, Brooklyn could win the championship without Kyrie Irving. I'm not saying that without him they will win, because he can definitely help them. But Kevin Durant cannot be stopped now, we saw it in the last playoffs. If he continues to fulfill this role and starts using his team a little better, I think they can win without Irving, ”said Pippen. Irving is suspended by the club because he cannot participate in home matches due to refusal of vaccinations.",
         "Date": "10-11-2021",
         "Source": "Twitter SiriusXM NBA Radio",
         "Image": "image11"],
        ["Id": "12",
         "Title": "Kevin Pangos named his newborn son after Bill Baron",
         "Subtitle": "Cleveland's Canadian point guard Kevin Pangos named his newborn son after his friend, Zenit defender Billy Baron. Because of the birth of the baby, Pangos misses the last games of his club. He is next to his wife and Billy, according to the Free Agent Telegram channel. The players spent last season together at Zenit. The Canadian finished the Euroleague with the following statistics - 13.5 points, 6.7 assists and 2 rebounds in 29 minutes on the floor, with 39% three-point conversion.",
         "Date": "10-11-2021",
         "Source": "Telegram channel Free Agent",
         "Image": "image12"],
        ["Id": "13",
         "Title": "Adrian Wojnarovski: Everyone is confident that Clay will truly return",
         "Subtitle": "ESPN insider Adrian Wojnarowski expects Golden State attacking defender Clay Thompson to return to form this season. “Now everyone in the league is whispering about Clay Thompson. Watching him, making inquiries with the Warriors. And they say that he is in good shape. I am not saying that he will return and immediately score 40 points in the first quarter. But he looks good in training and everyone is confident that, especially towards the end of the season, he will really be back, ”said Wojnarowski. Clay missed two seasons with a cruciate ligament rupture and then Achilles.",
         "Date": "10-11-2021",
         "Source": "Twitter NBA on ESPN",
         "Image": "image13"],
        ["Id": "14",
         "Title": "Richard Jefferson: If Morris hadn't pushed Jokic, Jokic wouldn't have pushed Morris",
         "Subtitle": "Former NBA player, now ESPN expert Richard Jefferson spoke about the clash between Nikola Jokic (Denver) and Markiff Morris (Miami). “It's simple. First, you can't do what Morris did. And you definitely can't do what Jokić did. But remember, if Morris hadn't done what he did, then Jokic wouldn't have done what he did, ”Jefferson said.",
         "Date": "9-11-2021",
         "Source": "Gennady Ilyin",
         "Image": "image14"],
        ["Id": "15",
         "Title": "James Harden scored a triple-double in a win against Magic",
         "Subtitle": " Nets defender James Harden scored a triple-double against Magic (123: 90). Harden has 17 points (6 out of 11 field goals), 11 rebounds and 11 assists in 30 minutes. We wanted to come back from the failure with Chicago and get rid of these bitterness of failure, - admitted James. Triple-double became for Harden 59th in his career.",
         "Date": "11-11-2021",
         "Source": "ESPN",
         "Image": "image15"]
        ]
    
    //MARK: - games
    let games: [[String : String]] = [
        ["id": "1",
         "Score": "112-104",
         "TopPlayer": "Jerami Grant",
         "City": "Boston",
         "Arena": "TD Garden",
         "Attackers": "Pistons",
         "Defenders": "Rockets",
         "Winner": "Pistons",
         "Date": "11-11-2021"],
        ["id": "2",
         "Score": "112-110",
         "TopPlayer": "Derrick Rose",
         "City": "Chicago",
         "Arena": "United Center",
         "Attackers": "Bucks",
         "Defenders": "Knicks",
         "Winner": "Bucks",
         "Date": "11-11-2021"],
        ["id": "3",
         "Score": "107-117",
         "TopPlayer": "Luka Doncic",
         "City": "Chicago",
         "Arena": "United Center",
         "Attackers": "Mavericks",
         "Defenders": "Bulls",
         "Winner": "Bulls",
         "Date": "11-11-2021"],
        ["id": "4",
         "Score": "88-104",
         "TopPlayer": "Scottie Barnes",
         "City": "New York",
         "Arena": "Madison Square Garden",
         "Attackers": "Raptors",
         "Defenders": "Celtics",
         "Winner": "Celtics",
         "Date": "11-11-2021"],
        ["id": "5",
         "Score": "111-100",
         "TopPlayer": "Malcolm Brogdon",
         "City": "Detroit",
         "Arena": "Little Caesars Arena",
         "Attackers": "Pacers",
         "Defenders": "Jazz",
         "Winner": "Pacers",
         "Date": "11-12-2021"],
        ["id": "6",
         "Score": "115-109",
         "TopPlayer": "Fred VanVleet",
         "City": "Philadelphia",
         "Arena": "Wells Fargo Center",
         "Attackers": "Raptors",
         "Defenders": "76ers",
         "Winner": "Raprots",
         "Date": "11-12-2021"],
        ["id": "7",
         "Score": "98-101",
         "TopPlayer": "Will Barton",
         "City": "Indiana",
         "Arena": "Gainbridge Fieldhouse",
         "Attackers": "Pacers",
         "Defenders": "Nuggets",
         "Winner": "Nuggets",
         "Date": "11-11-2021"],
        ["id": "8",
         "Score": "123-90",
         "TopPlayer": "James Harden",
         "City": "Orlando",
         "Arena": "Amway Center",
         "Attackers": "Nets",
         "Defenders": "Magic",
         "Winner": "Nets",
         "Date": "11-11-2021"],
        ["id": "9",
         "Score": "108-100",
         "TopPlayer": "Shai Gilgeous-Alexander",
         "City": "Oklahoma City",
         "Arena": "Paycom Center",
         "Attackers": "Thunder",
         "Defenders": "Pelicans",
         "Winner": "Thunder",
         "Date": "11-11-2021"],
        ["id": "10",
         "Score": "117-120",
         "TopPlayer": "Bam Adebayo",
         "City": "Los Angeles",
         "Arena": "STAPLES Center",
         "Attackers": "Heat",
         "Defenders": "Lakers",
         "Winner": "Lakers",
         "Date": "11-11-2021"],
        ["id": "11",
         "Score": "118-108",
         "TopPlayer": "Ja Morant",
         "City": "Memphis",
         "Arena": "FedExForum",
         "Attackers": "Hornets",
         "Defenders": "Grizzlies",
         "Winner": "Hornets",
         "Date": "11-11-2021"],
        ["id": "12",
         "Score": "109-119",
         "TopPlayer": "Frank Kaminsky",
         "City": "Portland",
         "Arena": "Moda Center",
         "Attackers": "Trail Blazers",
         "Defenders": "Suns",
         "Winner": "Suns",
         "Date": "11-11-2021"],
        ["id": "13",
         "Score": "98-110",
         "TopPlayer": "Kevin Huerter",
         "City": "Phoenix",
         "Arena": "Footprint Center",
         "Attackers": "Hawks",
         "Defenders": "Jazz",
         "Winner": "Jazz",
         "Date": "11-09-2021"],
        ["id": "14",
         "Score": "113-127",
         "TopPlayer": "Stephen Curry",
         "City": "New Orleans",
         "Arena": "Footprint Center",
         "Attackers": "Hawks",
         "Defenders": "Warriors",
         "Winner": "Warriors",
         "Date": "11-08-2021"],
        ["id": "15",
         "Score": "115-118",
         "TopPlayer": "Donovan Mitchell",
         "City": "Utah",
         "Arena": "Vivint Arena",
         "Attackers": "Jazz",
         "Defenders": "Heat",
         "Winner": "Heat",
         "Date": "11-06-2021"]
    ]
    
    //MARK: - teams
    let teams: [[String: String]] = [
        ["id": "1",
         "teamName": "Celtics",
         "Founded": "1946",
         "City": "Boston",
         "Arena": "TD Garden",
         "Head Coach": "Ime Udoka",
         "logoImage": "celtics-logo"],
        ["id": "2",
         "teamName": "Bulls",
         "Founded": "1966",
         "City": "Chicago",
         "Arena": "United Center",
         "Head Coach": "Billy Donovan",
         "logoImage": "bulls-logo"],
        ["id": "3",
         "teamName": "Hawks",
         "Founded": "1966",
         "City": "Chicago",
         "Arena": "United Center",
         "Head Coach": "Billy Donovan",
         "logoImage": "hawks-logo"],
        ["id": "4",
         "teamName": "Knicks",
         "Founded": "1946",
         "City": "New York",
         "Arena": "Madison Square Garden",
         "Head Coach": "Tom Thibodeau",
         "logoImage": "knicks-logo"],
        ["id": "5",
         "teamName": "Pistons",
         "Founded": "1948",
         "City": "Detroit",
         "Arena": "Little Caesars Arena",
         "Head Coach": "Dwane Casey",
         "logoImage": "pistons-logo"],
        ["id": "6",
         "teamName": "76ers",
         "Founded": "1949",
         "City": "Philadelphia",
         "Arena": "Wells Fargo Center",
         "Head Coach": "Doc Rivers",
         "logoImage": "76ers-logo"],
        ["id": "7",
         "teamName": "Pacers",
         "Founded": "1976",
         "City": "Indiana",
         "Arena": "Gainbridge Fieldhouse",
         "Head Coach": "Rick Carlisle",
         "logoImage": "pacers-logo"],
        ["id": "8",
         "teamName": "Magic",
         "Founded": "1989",
         "City": "Orlando",
         "Arena": "Amway Center",
         "Head Coach": "Jamahl Mosley",
         "logoImage": "magic-logo"],
        ["id": "9",
         "teamName": "Thunder",
         "Founded": "1967",
         "City": "Oklahoma City",
         "Arena": "Paycom Center",
         "Head Coach": "Mark Daigneault",
         "logoImage": "thunder-logo"],
        ["id": "10",
         "teamName": "Lakers",
         "Founded": "1948",
         "City": "Los Angeles",
         "Arena": "STAPLES Center",
         "Head Coach": "Frank Vogel",
         "logoImage": "lakers-logo"],
        ["id": "11",
         "teamName": "Grizzlies",
         "Founded": "1995",
         "City": "Memphis",
         "Arena": "FedExForum",
         "Head Coach": "Taylor Jenkins",
         "logoImage": "grizzlies-logo"],
        ["id": "12",
         "teamName": "Trail Blazers",
         "Founded": "1970",
         "City": "Portland",
         "Arena": "Moda Center",
         "Head Coach": "Chauncey Billups",
         "logoImage": "trail-blazers-logo"],
        ["id": "13",
         "teamName": "Suns",
         "Founded": "1968",
         "City": "Phoenix",
         "Arena": "Footprint Center",
         "Head Coach": "Monty Williams",
         "logoImage": "suns-logo"],
        ["id": "14",
         "teamName": "Pelicans",
         "Founded": "2002",
         "City": "New Orleans",
         "Arena": "Footprint Center",
         "Head Coach": "Willie Green",
         "logoImage": "pelicans-logo"],
        ["id": "15",
         "teamName": "Jazz",
         "Founded": "1974",
         "City": "Utah",
         "Arena": "Vivint Arena",
         "Head Coach": "Quin Snyder",
         "logoImage": "lazz-logo"],
    ]
    
    //MARK: - teamsLineUps
    let teamsLineUps: [String: [String]] = [
        "Celtics": ["Jayson Tatum","Jaylen Brown","Josh Richardson","Romeo Langford","Payton Pritchard","Grant Williams","Enes Kanter","Jabari Parker","Aaron Nesmith","Bruno Fernando"],
        "Bulls": ["Coby White","Lonzo Ball","Devon Dotson","Derrick Jones Jr.","Alex Caruso","Troy Brown Jr.","Zach LaVine","Nikola Vucevic","DeMar DeRozan","Ayo Dosunmu"],
        "Hawks": ["Delon Wright", "Jalen Johnson", "Sharife Cooper", "Kevin Huerter", "Skylar Mays", "Lou Williams", "Timothe Luwawu-Cabarrot", "Danilo Gallinari", "Gorgui Dieng", "Trae Young"],
        "Knicks": ["Obi Toppin", "Miles McBride", "Nerlens Noel", "Derrick Rose", "Immanuel Quickley", "Quentin Grimes", "Kemba Walker", "RJ Barrett", "Wayne Selden", "Evan Fournier"],
        "Pistons": ["Chris Smith", "Cade Cunningham", "Frank Jackson", "Hamidou Diallo", "Killian Hayes", "Trey Lyles", "Jerami Grant", "Isaiah Livers", "Kelly Olynyk", "Rodney McGruder"],
        "76ers": ["Coby White","Lonzo Ball","Devon Dotson","Derrick Jones Jr.","Alex Caruso","Troy Brown Jr.","Zach LaVine","Nikola Vucevic","DeMar DeRozan","Ayo Dosunmu"],
        "Pacers": ["Jayson Tatum","Jaylen Brown","Josh Richardson","Romeo Langford","Payton Pritchard","Grant Williams","Enes Kanter","Jabari Parker","Aaron Nesmith","Bruno Fernando"],
        "Magic": ["Obi Toppin", "Miles McBride", "Nerlens Noel", "Derrick Rose", "Immanuel Quickley", "Quentin Grimes", "Kemba Walker", "RJ Barrett", "Wayne Selden", "Evan Fournier"],
        "Thunder": ["Chris Smith", "Cade Cunningham", "Frank Jackson", "Hamidou Diallo", "Killian Hayes", "Trey Lyles", "Jerami Grant", "Isaiah Livers", "Kelly Olynyk", "Rodney McGruder"],
        "Lakers": ["Coby White","Lonzo Ball","Devon Dotson","Derrick Jones Jr.","Alex Caruso","Troy Brown Jr.","Zach LaVine","Nikola Vucevic","DeMar DeRozan","Ayo Dosunmu"],
        "Grizzlies": ["Jayson Tatum","Jaylen Brown","Josh Richardson","Romeo Langford","Payton Pritchard","Grant Williams","Enes Kanter","Jabari Parker","Aaron Nesmith","Bruno Fernando"],
        "Trail Blazers": ["Obi Toppin", "Miles McBride", "Nerlens Noel", "Derrick Rose", "Immanuel Quickley", "Quentin Grimes", "Kemba Walker", "RJ Barrett", "Wayne Selden", "Evan Fournier"],
        "Suns": ["Jayson Tatum","Jaylen Brown","Josh Richardson","Romeo Langford","Payton Pritchard","Grant Williams","Enes Kanter","Jabari Parker","Aaron Nesmith","Bruno Fernando"],
        "Pelicans": ["Coby White","Lonzo Ball","Devon Dotson","Derrick Jones Jr.","Alex Caruso","Troy Brown Jr.","Zach LaVine","Nikola Vucevic","DeMar DeRozan","Ayo Dosunmu"],
        "Jazz": ["Chris Smith", "Cade Cunningham", "Frank Jackson", "Hamidou Diallo", "Killian Hayes", "Trey Lyles", "Jerami Grant", "Isaiah Livers", "Kelly Olynyk", "Rodney McGruder"]
    ]
    
    private init() {}
}
